name: 01-building blocks
on: [push, workflow_dispatch]
jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps:
            - name: hello
              run: |
                echo "Hello,World!"
                exit 1
    echo-goodbye:
        runs-on: ubuntu-latest
        steps:
            - name: Fails step
              run: |
                echo "I will fail"
                exit 0
            - name: Say goodbye
              run: echo "Goodbye!"