# name: 04-Using-Actions
# on: [workflow_dispatch]
# jobs:
#     build-to-the-workflow:
#         runs-on: ubuntu-latest
#         steps:
#             - name: Checkout Code
#               uses: actions/checkout@v4
#             - name: Printing Folders
#               run: tree
#             - name: Setup Node
#               uses: actions/setup-node@v4
#               with:
#                 node-version: '20.x'
#             - name: Install Dependencies
#               run: |
#                 cd react-app
#                 npm ci
#             - name: Run Unit Tests
#               run: |
#                 cd react-app
#                 npm run test
      # instead of cd react-app
      # working-directory: action/react-app


name: 04-Using-Actions
on: [push]
jobs:
    build-to-the-workflow:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: react-app
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Printing Folders
              run: tree
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: '20.x'
            - name: Install Dependencies
              run: npm ci
            - name: Run Unit Tests
              run: 
                npm run test