name: commitid-branch-identification
on:
    workflow_run:
        workflows: Workflow Runners
        types: 
            - completed
jobs:
    commitid-branch:
        runs-on: ubuntu-latest
        steps:
            - name: commitid-branch-details
              uses: actions/checkout@v4
            - run: |
                echo $GITHUB_SHA
                echo $GITHUB_REF