name: commitid-branch-identification
on: [push, pull_request, issues]
jobs:
    commitid-branch:
        runs-on: ubuntu-latest
        steps:
            - name: commitid-branch-details
              uses: actions/checkout@v4
            - run: |
                echo $GITHUB_SHA
                echo $GITHUB_REF