name: workflow-event
on:
    push:
    pull_request:
    workflow_dispatch:
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: enent-type
              run: echo "${{github.event_name}}"